Simplify handling of dependency changes (#1048)
Currently, if you change any of the dependency info (e.g. add a package
to `env/debian/pkgs.txt`), circleci will fail during the `build_prep`
stage, and none of the tests will be run. This change adds a `env/x/check`
counterpart to `env/x/deps`. `docker/deps_check` runs each `/check` to
see if dependencies have changed. If they have, it's treated as a
soft-fail on circleci, allowing all the tests to run, and reporting
failure during the `post_check` step. This allows a single PR to update
dependencies and the relevant code. The process looks like this:

- Submit a PR as normal, containing both dependency and code changes.
- When the PR has been LGTM'd, and circleci passes the build apart from
  the dependency soft-fail, a new version of `scion_base` will be built
  from that PR and published.
- The PR is then updated with the new `scion_base` image hash in
  `.circleci/config.yml`, and can be submitted.

Also:
- Make docker.sh clean smarter
- Don't tag `latest` by default on scion_base

diff --git a/docker/deps_check b/docker/deps_check
--- a/docker/deps_check
+++ b/docker/deps_check
@@ -1,20 +1,26 @@
 #!/bin/bash
 
 ret=0
+
 check() {
-    cmp "$1" "$2"
-    ret=$((ret+$?))
+    echo "Check: $@"
+    # If a check errors, exit immediately.
+    output=$("$@") || { echo "ERROR: non-zero result"; exit 1; }
+    if [ -n "$output" ]; then
+        # If a `check` produced any output, count it as a failure.
+        ret=$((ret+1))
+        echo "$output"
+    fi
 }
 
-cd env
-for f in common.sh */*; do
-    check "$f" "/tmp/build/$f"
+for f in env/*/check; do
+    check "$f"
 done
-cd ..
-
-check go/vendor/vendor.json /tmp/build/go_vendor.json
+check bash -c "cd go && govendor sync -n"
 
 if [ $ret -ne 0 ]; then
+    echo "============================================================"
     echo "ERROR: outdated dependencies, scion_base needs to be rebuilt"
+    echo "============================================================"
 fi
 exit $ret
