pubpr1847

diff --git a/go/Makefile b/go/Makefile
--- a/go/Makefile
+++ b/go/Makefile
@@ -1,4 +1,4 @@
-.PHONY: all clean test coverage lint deps_gen deps depspurge proto bin libs hsr
+.PHONY: all clean test coverage lint deps_gen deps depspurge proto mocks bin libs hsr
 
 SHELL=/bin/bash
 LOCAL_DIRS = $(shell find * -maxdepth 0 -type d | grep -v '^vendor$$')
@@ -6,6 +6,9 @@ LOCAL_PKGS = $(patsubst %, ./%/..., $(LOCAL_DIRS))
 LOCAL_GOBIN = $(shell realpath -s $$PWD/../bin)
 LOCAL_NONGEN = $(shell find ${LOCAL_DIRS} -type f -iname '*.go' -a '!' -iname '*.capnp.go' -a '!' -iname 'mock_*.go')
 GOTAGS = assert
+MOCK_SRC_IN = lib/infra/common.go lib/pathdb/pathdb.go lib/snet/snetproxy/interface.go lib/snet/snetproxy/reconnecter.go lib/snet/snetproxy/io.go
+MOCK_SRC_OUT = $(shell for i in $(MOCK_SRC_IN); do fn=$$(basename "$$i"); dn=$$(dirname "$$i"); pn=$$(basename "$$dn"); echo "$$dn/mock_$$pn/mock_$$fn"; done)
+MOCK_SRC_DIRS = $(shell for i in $(MOCK_SRC_IN); do dn=$$(dirname "$$i"); pn=$$(basename "$$dn"); echo "$$dn/mock_$$pn"; done | sort -u)
 
 all: deps_gen bin libs
 
@@ -14,7 +17,6 @@ clean:
 	GOBIN=${LOCAL_GOBIN} go clean ${LOCAL_PKGS}
 	go clean -i ./vendor/...
 	cd proto && $(MAKE) clean
-	find . -name "mock_*.go" -delete
 
 test: deps_gen
 	GOCONVEY_REPORTER=story govendor test +local
@@ -35,17 +37,17 @@ lint:
 	@echo "======> go vet"
 	go vet ${LOCAL_PKGS}
 
-mocks_prep:
-	./genmocks.sh prepare
-
-mocks: deps
-	./genmocks.sh mock
 
 deps_gen: deps proto mocks
 
-deps: vendor/.deps.stamp ../proto/go.capnp
+deps: vendor/.deps.stamp ../proto/go.capnp mocks
+	@if [ -n "$$(govendor list -no-status +outside | grep -v '^context$$')" ]; then \
+	    echo "ERROR: external/missing packages:"; \
+	    govendor list +outside; \
+	    exit 1; \
+	fi;
 
-vendor/.deps.stamp: mocks_prep vendor/vendor.json
+vendor/.deps.stamp: vendor/vendor.json
 	@[ -z "${QUIET}" ] && echo "$$(date -Iseconds) Remove unused deps"; \
 	    govendor list -no-status +unused | while read pkg; do \
 	    grep -q '"path": "'$$pkg'"' vendor/vendor.json && continue; \
@@ -54,11 +56,6 @@ vendor/.deps.stamp: mocks_prep vendor/vendor.json
 	done
 	@[ -z "${QUIET}" ] && echo "$$(date -Iseconds) Syncing deps"; govendor sync -v
 	@[ -z "${QUIET}" ] && echo "$$(date -Iseconds) Installing deps"; go install ./vendor/...
-	@if [ -n "$$(govendor list -no-status +outside | grep -v '^context$$')" ]; then \
-	    echo "ERROR: external/missing packages:"; \
-	    govendor list +outside; \
-	    exit 1; \
-	fi;
 	touch $@
 
 ../proto/go.capnp:
@@ -71,6 +68,14 @@ depspurge:
 
 proto: deps
 	$(MAKE) -C proto
+
+mocks: $(MOCK_SRC_DIRS) $(MOCK_SRC_OUT)
+
+$(MOCK_SRC_DIRS):
+	@mkdir $@
+
+mock_%.go: ../%.go
+	mockgen -destination=$@ -source=$$(realpath -s --relative-to . $<)
 
 bin: deps_gen
 	GOBIN=${LOCAL_GOBIN} govendor install --tags "$(GOTAGS)" -v +local,program
