comments

diff --git a/tools/ci/common b/tools/ci/common
--- a/tools/ci/common
+++ b/tools/ci/common
@@ -1,24 +1,20 @@
-#!/bin/bash
-
 usage() {
     echo "Usage: $0: [-d]\n"
     exit 1
 }
 
-opts() {
-    while getopts ":d" opt; do
-        case "$opt" in
-            d)
-                DOCKER=true
-                ;;
-            \?)
-                echo "Invalid option: -$OPTARG" >&2
-                usage
-                ;;
-            *)
-                usage
-                ;;
-        esac
-    done
-    shift $((OPTIND-1))
-}
+while getopts ":d" opt; do
+    case "$opt" in
+        d)
+            DOCKER=true
+        ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+        ;;
+        *)
+            usage
+        ;;
+    esac
+done
+shift "$((OPTIND-1))"
