acceptance: de-flake cert_renewal and hidden_paths (#4399)
These tests have become even more flaky with the updated CI runners; it seems
that this is triggered due to using the significantly quicker docker-compose v2.

Use the existing await-connectivity script to determine when a test can
safely start to run, instead of sleeping for arbitrary number of seconds.

diff --git a/tools/await-connectivity b/tools/await-connectivity
--- a/tools/await-connectivity
+++ b/tools/await-connectivity
@@ -13,7 +13,7 @@
 # 
 # Usage: await-connectivity -q QUIET -t TIMEOUT
 
-set -euo pipefail
+set -Eeuo pipefail
 
 QUIET=10
 TIMEOUT=20
@@ -83,6 +83,7 @@ main() {
   parse_opts "$@"
 
   # poor bash-man's yaml parser
+  stat gen/as_list.yml > /dev/null # ensure file exists; command substitutions below don't fail because local (!?)
   local cores=$(sed -n '1,/Non-core/{s/^- //p}' gen/as_list.yml)
   local noncores=$(sed -n '/Non-core/,${s/^- //p}' gen/as_list.yml)
 
